import { useEffect, useState } from 'react';
import { Calendar, Clock, User, Search } from 'lucide-react';
import { apiFetch, postJson } from '../../api';
import { StatusBadge } from '../shared/StatusBadge';
import type { Appointment, AppointmentStatus } from '../../types';

export function DoctorSchedule({ staffName }: { staffName: string }) {
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<AppointmentStatus | 'All'>('All');
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');
  const load = () => apiFetch<{ ok: boolean; appointments: Appointment[] }>('/api/staff/schedule').then(d => setAppointments(d.appointments)).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const updateStatus = async (id: string, newStatus: AppointmentStatus) => { setMessage(''); try { await postJson(`/api/staff/appointments/${id}/status`, { status: newStatus }); await load(); setMessage('Appointment updated.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Could not update appointment.'); } };
  const filtered = appointments.filter(a => (status === 'All' || a.status === status) && (!search || a.patientName.toLowerCase().includes(search.toLowerCase()) || a.reason.toLowerCase().includes(search.toLowerCase())));
  if (loading) return <div className="text-slate-500">Loading schedule...</div>;
  return <div className="space-y-6"><div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><p className="font-semibold text-slate-900">Schedule for {staffName}</p><p className="text-sm text-slate-500">Update appointment status after patient visits.</p></div>{message && <div className="bg-blue-50 text-blue-700 border border-blue-100 rounded-2xl p-4 text-sm">{message}</div>}<div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search patient or reason" className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white" /></div><select value={status} onChange={e => setStatus(e.target.value as AppointmentStatus | 'All')} className="px-4 py-2.5 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white text-slate-700">{['All','Booked','Completed','Cancelled','Missed'].map(s => <option key={s}>{s}</option>)}</select></div><div className="space-y-3">{filtered.map(a => <div key={a.id} className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4"><div className="flex items-start gap-4"><div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center"><User size={18} className="text-blue-600" /></div><div><p className="font-semibold text-slate-900">{a.patientName}</p><div className="flex flex-wrap gap-4 mt-2 text-sm text-slate-500"><span className="flex items-center gap-1"><Calendar size={14} />{new Date(a.date).toLocaleDateString('en-GB')}</span><span className="flex items-center gap-1"><Clock size={14} />{a.time}</span></div>{a.reason && <p className="text-sm text-slate-500 mt-2">Reason: {a.reason}</p>}</div></div><div className="flex flex-col sm:items-end gap-2"><StatusBadge status={a.status} /><div className="flex flex-wrap gap-2">{(['Completed','Missed','Cancelled'] as AppointmentStatus[]).map(s => <button key={s} disabled={a.status === s} onClick={() => updateStatus(a.id, s)} className="px-3 py-1.5 text-xs rounded-lg border border-slate-200 text-slate-600 hover:bg-slate-50 disabled:opacity-50">{s}</button>)}</div></div></div></div>)}{filtered.length === 0 && <div className="bg-white rounded-2xl border border-slate-100 p-12 text-center"><Calendar size={40} className="text-slate-300 mx-auto mb-4" /><p className="text-slate-500">No appointments found.</p></div>}</div></div>;
}
